blog/urls.py
from django.urls import path, include, reverse
from .views import *
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from blog.views import login,join, eventcreate

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'blog', BlogViewSet)


app_name = 'blog'

urlpatterns = [
    path('passchform/', password_change_form, name="password_change"),
    path('logout/', logout, name="logout"),
    path('userevent/', event_user_page, name="event_user"),
    path('create/', EventCreate.as_view(), name="create_event"),
    path('register/', register, name="reg"),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', BlogViews, name='home'),
    path('blog/<slug:slug>/', BlogDetail, name='detail'),
    path('signup/', SignUp, name='signup'),
    path('success/', Success, name='success'),
    path('contact/', Contact, name='contact'),
    path('login/', login, name="login"),
    path('esas/', login_required, name="login"),
    path('join/', join, name="joinevent")
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

facebook_register/urls.py
from django.urls import path 
urlpatterns = [
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/',include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone

# Create your models here.
class Blog(models.Model):
    Title = models.CharField(max_length=200)
    Image = models.ImageField()
    Content = RichTextUploadingField(config_name='default')
    Tag = models.CharField(max_length=100)
    Slug = models.SlugField(max_length=200, unique=True)
    Date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.Title

    def __unicode__(self):
        return u'%s' % self.Title
    
    class Meta:
        ordering = ('-Date',)


class Comment(models.Model):
    Post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    Name = models.CharField(max_length=100)
    Email = models.EmailField(max_length=200)
    Body = models.TextField()
    Created = models.DateTimeField(auto_now_add=True)
    Active = models.BooleanField(default=True)
    Parent = models.ForeignKey('self', on_delete=models.CASCADE, null= True, blank=True, related_name='replies')

    class Meta:
        ordering = ('-Created',)

    def __str__(self):
        return 'Comment By {}'.format(self.Name)

class Category(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    start_time = models.CharField(max_length=255 ,default=timezone.now())
    appointment_time = models.DateTimeField(default=timezone.now)
    img = models.ImageField(upload_to='event')
    category = models.ForeignKey('Category',on_delete=models.CASCADE,related_name='events')

    def __str__(self):
        return self.name

blog/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from .models import *
from .form import *
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from .serializers import *
from django.views.generic.edit import CreateView, FormView
from django.views.generic import ListView
from .models import Event
# Create your views here.

class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

class BlogViewSet(viewsets.ModelViewSet):
    queryset = Blog.objects.all().order_by('-Date')
    serializer_class = BlogSerializer

def register(request):
    return render(request, 'blog/signup.html')

def login(request):
    return render(request, 'blog/login.html')

def BlogViews(request):
    posts = Blog.objects.all()
    return render(request, 'blog/index.html', { 'post': posts })

def Success(request):
    return render(request, 'blog/success.html')

def BlogDetail(request, slug):
    post = get_object_or_404(Blog, Slug = slug)
    comments = post.comments.filter(Active=True, Parent__isnull=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid:
            Parent_obj = None
            try:
                Parent_id = int(request.POST.get('Parent_id'))
            except:
                Parent_id = None
            if Parent_id:
                Parent_obj = Comment.objects.get(id=Parent_id)
                if Parent_obj:
                    reply_comment = comment_form.save(commit=False)
                    reply_comment.Parent = Parent_obj
            new_comment = comment_form.save(commit=False)
            new_comment.Post = post
            new_comment.save()
            return redirect('blog:detail', slug)
    else:
        comment_form = CommentForm()

    return render(request, 'blog/blogdetail.html', {'blog':post, 'comments':comments, 'comment_form':comment_form})


def SignUp(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('blog:success')
    else:
        form = UserRegisterForm()
    return render(request, "registration/signup.html", {'form': form})



def Contact(request):
    Contact_Form = ContactForm
    if request.method == 'POST':
        form = Contact_Form(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get('contact_name')
            contact_email = request.POST.get('contact_email')
            contact_content = request.POST.get('content')

            template = get_template('blog/contact_form.txt')
            context = {
                'contact_name' : contact_name,
                'contact_email' : contact_email,
                'contact_content' : contact_content,
            }
            
            content = template.render(context)

            email = EmailMessage(
                "New contact form email",
                content,
                "Tewaves Project" + '',
                ['emka6451@gmail.com'],
                headers = { 'Reply To': contact_email }
            )

            email.send()

            return redirect('blog:success')
    return render(request, 'blog/contact.html', {'form':Contact_Form })

def join(request):
    return render(request, 'blog/join_events.html')

def logout(request):
    return render(request, 'blog/base.html')

def password_change_form(request):
    return render(request, 'registration/password_change_form.html')

def eventcreate(request):
    return render(request, 'blog/create.html')

def event_user_page(request):
    return render(request, 'blog/event_user_page.html')


class EventCreate(CreateView):
    model = Event
    form_class = EventForm
    # fields = ['name','description','start_time','img','category','appointment_time']
    template_name = 'blog/create.html'
    success_url = '/'

    def save(self, *args, **kwargs):

        print("AAA", args, kwargs)

facebook_register/views.py
from . import urls
from django.shortcuts import render
# Create your views here.
def index(request):
    return render(request, "user/index.html")

blog/templates/blog/base.html
{% load socialaccount %}
<!DOCTYPE html>
{% load static %}

<html>
    <head>
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
      <!--Import materialize.css-->
      <link rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>
    <body>
    <nav>
      <div class="container">
        <div class="nav-wrapper">

          <a href="{% url 'blog:home' %}" class="brand-logo">Logo</a>
          
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            
            <li><a href="{% url 'blog:contact' %}">Contact</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'blog:logout' %}">Log Out</a></li>
            <li><a href="{% url 'blog:password_change' %}">Change Password</a></li>
            {% else %}
            <li><a href="{% url 'blog:signup' %}">Sign Up</a></li>
            <li><a href="">Log In</a></li>
            {% endif %}

          </ul> 
        </div>
      </div>
    </nav>

        {% block content %}

        {% endblock %}
      <!--JavaScript at end of body for optimized loading-->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="{% static 'materialize/js/materialize.min.js' %}"></script>
    </body>
  </html>
        

blog/templates/blog/blogdetail.html
{% extends "blog/base.html" %}
{% load tz %}
{% block content %}

<div class="container">
<div class="row">
    <div class="col l12">
        <div class="card blue-grey">
            <div class="card-image">
                <img src="{{ blog.Image.url }}"/>
                <span class="card-title">{{ blog.Title | title}}</span>
            </div>
            <div class="card-content white-text">
                <span>{{ blog.Date }}</span>
                <p> {{ blog.Content | safe }} </p>
            </div>
        </div>
    </div>
</div>

<!-- comment -->
<div class="row">
            <form method="post" class="col l12">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col l8">
                        <i class="material-icons prefix">account_circle</i>
                        {{ comment_form.Name }}
                        <label for="id_Name">Name</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col l8">
                        <i class="material-icons prefix">email</i>
                        {{ comment_form.Email }}
                        <label for="id_Email">Email</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col l8">
                        <i class="material-icons prefix">mode_edit</i>
                        {{ comment_form.Body }}
                        <label for="id_Body">Comment</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col l5">
                        <button class="btn waves-effect waves-light" type="submit">Comment</button>
                    </div>
                </div>
            </form>
</div>

<!-- comment list -->

{% for comment in comments %}

<div class="row">
    <div class="col l12 s12">
        <div class="card-panel blue darken-4">
            <div class="card-content white-text">
                <span>{{ comment.Name | title | linebreaks }}</span>
                <span>{{ comment.Created | localtime }}</span>
                <p>{{ comment.Body | linebreaks }}</p>
            </div>
        </div>
    </div>
</div>

    {% for reply in comment.replies.all %}

    <div class="row">
        <div class="col s10 offset-s2">
            <div class="card-panel  blue darken-1">
                <div class="card-content white-text">
                    <span>{{ reply.Name | title | linebreaks }}</span>
                    <span>{{ reply.Created | localtime }}</span>
                    <p>{{ reply.Body | linebreaks }}</p>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}

    <div class="row">
    <div class="col s10 offset-s2">
            <form method="post" class="col l6 ">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col l6">
                        <i class="material-icons prefix">account_circle</i>
                        {{ comment_form.Name }}
                        <label for="id_Name">Name</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col l10">
                        <i class="material-icons prefix">email</i>
                        {{ comment_form.Email }}
                        <label for="id_Email">Email</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col l10">
                        <i class="material-icons prefix">mode_edit</i>
                        {{ comment_form.Body }}
                        <label for="id_Body">Comment</label>
                    </div>
                </div>
                <input type="hidden" name="Parent_id" value="{{ comment.id }}">
                <div class="row">
                    <div class="col l5">
                        <button class="btn waves-effect waves-light" type="submit">Reply</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% empty %}

    <div class="row">
        <div class="col l12 s12">
            <div class="card-panel  blue darken-1">
                <div class="card-content white-text">
                    <span>There is no comment....</span>
                </div>
            </div>
        </div>
    </div>

{% endfor %}

</div>
{% endblock %}

blog/templates/blog/contact.html
{% extends "blog/base.html" %}


{% block content %}
<div class="container">
    <div  class="row">
        <div  class="col l12">
            <h1>Contact form</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
            <button class="btn waves-effect waves-light" type="submit">Send Email</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/contact1.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{%static 'css/contact.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css">  <title>ToWaves</title>
</head>
<body>
  <header>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
          <div class="logo"><img src="{%static 'img/logoo.png' %}"></div>
          <nav>
          <ul>
            <li><a href="#" >Create Event</a> </li>
            <li><a href="#">Login</a> </li>
            <li><a href="#">Sign up</a></li>
          
          </ul>
        </nav>
    <div class="menu-toggle" ><i class="fas fa-bars"></i>
    
    </div> 
      </div>
    </div>
  </div>
</header>
  <div class="container">
    <div class="row">
      <div class="col-md-12 contact">
      <h1 class="display-3">Contact Us</h1>
    </div>
    </div>
  </div>
<section class="container">

    
  
    <div class="row">
  
      <div class="col-lg-12 mb-lg-0 mb-4">
  
        <div class="card">
          <div class="card-body">
            <!-- Header -->
            <div class="form-header blue accent-1">
              <h3 class="mt-2"><i class="fas fa-envelope"></i> Write to us:</h3>
            </div>
            <p class="dark-grey-text">We'll write rarely, but only the best content.</p>
            <!-- Body -->
            <div class="col-md-6 md-form">
              <i class="fas fa-user prefix grey-text"></i>
              <input type="text" id="form-name" class="form-control">
              <label for="form-name">Your name</label>
            </div> <div class="col-md-6 md-form">
                <i class="fas fa-user prefix grey-text"></i>
                <input type="text" id="form-name" class="form-control">
                <label for="form-name">Your Surename</label>
              </div>
            <div class="col-md-12 md-form">
              <i class="fas fa-envelope prefix grey-text"></i>
              <input type="text" id="form-email" class="form-control">
              <label for="form-email">Your email</label>
            </div>
            <div class="col-md-12 md-form">
              <i class="fas fa-tag prefix grey-text"></i>
              <input type="text" id="form-Subject" class="form-control">
              <label for="form-Subject">Subject</label>
            </div>
            <div class="col-md-12 md-form">
              <i class="fas fa-pencil-alt prefix grey-text"></i>
              <textarea id="form-text" class="form-control md-textarea" rows="3"></textarea>
              <label for="form-text">Send message</label>
            </div>
            <div class="text-center">
              <button class="btn btn-light-blue">Submit</button>
            </div>
          </div>
        </div>
        <!-- Form with header -->
  
      </div>
      <!-- Grid column -->
  
      <!-- Grid column -->
      <div class="col-lg-12">
  
        <!--Google map-->
        <div id="map-container-section" class="z-depth-1-half map-container-section mb-4" style="height: 400px">
          <iframe src="https://maps.google.com/maps?q=Baku&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0"
            style="border:0" allowfullscreen></iframe>
        </div>
        <!-- Buttons-->
        <div class="row text-center">
          <div class="col-md-4">
            <a class="btn-floating blue accent-1">
              <i class="fas fa-map-marker-alt"></i>
            </a>
            <p>Baku</p>
            <p class="mb-md-0">Azerbaijan</p>
          </div>
          <div class="col-md-4">
            <a class="btn-floating blue accent-1">
              <i class="fas fa-phone"></i>
            </a>
            <p>+ 01 234 567 89</p>
            <p class="mb-md-0">Mon - Fri, 8:00-22:00</p>
          </div>
          <div class="col-md-4">
            <a class="btn-floating blue accent-1">
              <i class="fas fa-envelope"></i>
            </a>
            <p>info@gmail.com</p>
            <p class="mb-0">sale@gmail.com</p>
          </div>
        </div>
  
      </div>
      <!-- Grid column -->
  
    </div>
    <!-- Grid row -->
  
  </section>

 

  <footer class="footer-distributed">

        <div class="footer-right">

          <a class="btn-floating btn-fb mx-1">
            <i class="fab fa-facebook-f"> </i>
          </a> 
          
          <a class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text mr-4"> </i>
          </a>
         
        </div>

        <div class="footer-left">

          <p class="footer-links">
            <a href="#">Home</a>

            <a href="#">Events</a>

            <a href="#">Contact us</a>

            <a href="#">About</a>

            <a href="#">English</a>

          </p>
          <hr style="background-color:grey !important;">

          <p>Company Name &copy; 2019 by Towaves</p>
        </div>

      </footer>
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script type="text/javascript">
  $(document).ready(function(){
    $('.menu-toggle').click(function(){
      $('nav').toggleClass('active')
    })
  })
  </script>
</body>
</html>

blog/templates/blog/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/create.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
    integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css">
  <title>ToWaves</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

  <title>ToWaves</title>
</head>

<body>
  <nav class="navbar navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a href="#" class="navbar-brand">
          <img style="width: 119.73; height:49.5px;" src="{%static 'img/Group 264@2x.png' %}"> </a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
          data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span style="background-color: black;" class="icon-bar"></span>
          <span style="background-color: black;" class="icon-bar"></span>
          <span style="background-color: black;" class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a style="border-right: 1px solid black;" href="#">Create Event</a></li>
          <li><a style="color: black;" href="./login.html">Login</a></li>
          <li><a style="color: black;" href="./signin.html">Sign Up</a></li>

        </ul>
      </div>
    </div>
  </nav>
  <div class="container-1">

    <div class="col-lg-12 mb-lg-0 mb-4">

      <div class="card">
        <div class="card-body">


          <div class="col-md-12 md-form">
            <p class="par">Event Name *</p>
            <p class="numb">0/62</p>
            <input value="Name" type="text" id="form-name" class="form-control">
            <br>
          </div>

          <div class="col-md-12 md-form">
            <p class="">Select Category </p>
            <button>
              Music
            </button>
            <button>
              Visual Arts
            </button>
            <button>
              Performing Arts
            </button>
            <button>
              Film
            </button>
            <button>
              Lectures
            </button>
            <button>
              Books
            </button>
            <button>
              Food&Drink
            </button>
            <button>
              Nightlife
            </button>
            <br><br>

          </div>

          <div class="col-md-12 md-form">
            <p class=""> Description</p>

            <textarea id="form-text" class="form-control md-textarea" placeholder="Write your description" rows="3"></textarea>
            <label for="form-text">Send message</label>
          </div>
          <div class="col-md-12 md-form">
            <div class="custom-select" style="width:200px;">
              <select>
                <option value="0">Choose Your Adress</option>
                <option  value="1" onclick="myFunction()" id="map"></option>

              </select>
            </div>
            <br>
            <br>

          </div>
          <div class="col-md-12 md-form">
            <table>
              <tr>
                <p style="float: left;">Starts:</p>
                <br>
                <br>
                <td><input type="datetime-local" value="2014-06-19T21:30" /></td>
              </tr>
            </table>
            <br>
            <br>
          </div>


          <div class="col-md-12 md-form">
            <label for="appt-time">Choose an appointment time: </label>
            <input id="appt-time" type="time" name="appt-time" value="13:30">
            <br>
            <br>
          </div>
          <div class="col-md-12 md-form">
            <div class="text-center">
                <div style="width: 20rem;">
                    <img class="card-img-top" src="{%static 'img/3901.png'%}" alt="Card image cap">
                    <div class="card-block">
                        <form action="#type your action here" method="POST" enctype="multipart/form-data" name="myForm">
                          <div id="yourBtn" onclick="getFile()">click to upload a file</div>
                          <!-- this is your file input tag, so i hide it!-->
                          <!-- i used the onchange event to fire the form submission-->
                          <div style='height: 0px;width: 0px; overflow:hidden;'><input id="upfile" type="file" value="upload" onchange="sub(this)" /></div>
                          <!-- here you can have file submit button or you can write a simple script to upload the file automatically-->
                          <!-- <input type="submit" value='submit' > -->
                        </form>
                    </div>
                  </div>
                
                
            </div>
            <br>
            <br>
          </div>
          <div class="col-md-12 md-form">
            <div class="text-center">
              <button class="sub btn-light-blue">Create Event</button>
            </div>
          </div>

          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>


        </div>

      </div>
    </div>
  </div>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCHBogTzzKWBngIxwUwHV_VbQX9rHuL0ZE&callback=initMap"
    async defer></script>
  <script>
      function getFile() {
        document.getElementById("upfile").click();
      }
      
      function sub(obj) {
        var file = obj.value;
        var fileName = file.split("\\");
        document.getElementById("yourBtn").innerHTML = fileName[fileName.length - 1];
        document.myForm.submit();
        event.preventDefault();
      }
  </script>
  <script>
    var x, i, j, selElmnt, a, b, c;

    x = document.getElementsByClassName("custom-select");
    for (i = 0; i < x.length; i++) {
      selElmnt = x[i].getElementsByTagName("select")[0];
    
      a = document.createElement("DIV");
      a.setAttribute("class", "select-selected");
      a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
      x[i].appendChild(a);
   
      b = document.createElement("DIV");
      b.setAttribute("class", "select-items select-hide");
      for (j = 1; j < selElmnt.length; j++) {
   
        c = document.createElement("DIV");
        c.innerHTML = selElmnt.options[j].innerHTML;
        c.addEventListener("click", function (e) {
    
          var y, i, k, s, h;
          s = this.parentNode.parentNode.getElementsByTagName("select")[0];
          h = this.parentNode.previousSibling;
          for (i = 0; i < s.length; i++) {
            if (s.options[i].innerHTML == this.innerHTML) {
              s.selectedIndex = i;
              h.innerHTML = this.innerHTML;
              y = this.parentNode.getElementsByClassName("same-as-selected");
              for (k = 0; k < y.length; k++) {
                y[k].removeAttribute("class");
              }
              this.setAttribute("class", "same-as-selected");
              break;
            }
          }
          h.click();
        });
        b.appendChild(c);
      }
      x[i].appendChild(b);
      a.addEventListener("click", function (e) {
  
        e.stopPropagation();
        closeAllSelect(this);
        this.nextSibling.classList.toggle("select-hide");
        this.classList.toggle("select-arrow-active");
      });
    }
    function closeAllSelect(elmnt) {
    
      var x, y, i, arrNo = [];
      x = document.getElementsByClassName("select-items");
      y = document.getElementsByClassName("select-selected");
      for (i = 0; i < y.length; i++) {
        if (elmnt == y[i]) {
          arrNo.push(i)
        } else {
          y[i].classList.remove("select-arrow-active");
        }
      }
      for (i = 0; i < x.length; i++) {
        if (arrNo.indexOf(i)) {
          x[i].classList.add("select-hide");
        }
      }
    }

    document.addEventListener("click", closeAllSelect);

    function myFunction() {
      // New map
      var map = new google.maps.Map(document.getElementById('map'), options);

      // Listen for click on map
      google.maps.event.addListener(map, 'click', function(event){
        // Add marker
        addMarker({coords:event.latLng});
      });

      // Array of markers
      var markers = [
        {
          coords:{lat:42.4668,lng:-70.9495},
          iconImage:'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png',
          content:'<h1>Lynn MA</h1>'
        },
        {
          coords:{lat:42.8584,lng:-70.9300},
          content:'<h1>Amesbury MA</h1>'
        },
        {
          coords:{lat:42.7762,lng:-71.0773}
        }
      ];

      // Loop through markers
      for(var i = 0;i < markers.length;i++){
        // Add marker
        addMarker(markers[i]);
      }

      // Add Marker Function
      function addMarker(props){
        var marker = new google.maps.Marker({
          position:props.coords,
          map:map,
          //icon:props.iconImage
        });

        // Check for customicon
        if(props.iconImage){
          // Set icon image
          marker.setIcon(props.iconImage);
        }

        // Check content
        if(props.content){
          var infoWindow = new google.maps.InfoWindow({
            content:props.content
          });

          marker.addListener('click', function(){
            infoWindow.open(map, marker);
          });
        }
      }
      console.log("AAAA", coords)
    }

  </script>
</body>

</html>

blog/templates/blog/event_user_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

blog/templates/blog/success.html
{% extends "blog/base.html" %}
{% load tz %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col l12">
            <h1>Succesfullly Send</h1>
        </div>
    </div>
</div>


{% endblock %}